blank_issues_enabled: false
contact_links:
  - name: Contribution style guide
    url: https://github.com/kaisekidev/kaiseki-org/blob/master/docs/governance/contribution-style.md
    about: How we write issues, PRs, commits, and branches.
